# Generated by Django 4.2.5 on 2023-10-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='is_validated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
