# Generated by Django 4.2.5 on 2023-10-22 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0005_alter_mediafile_file_alter_mediafile_file_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_manager.mediafile'),
        ),
        migrations.AlterField(
            model_name='notificationssourcemedia',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_manager.sourcemediafile'),
        ),
    ]
