# Generated by Django 4.2.5 on 2023-10-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0006_alter_notifications_media_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notifications',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='notificationssourcemedia',
            table='source_notifications',
        ),
    ]
