# Generated by Django 4.2.5 on 2023-10-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0008_notifications_user_notificationssourcemedia_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mediafile',
            table='medias',
        ),
        migrations.AlterModelTable(
            name='sourcemediafile',
            table='sources',
        ),
    ]
