# Generated by Django 4.2.5 on 2023-10-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0009_alter_mediafile_table_alter_sourcemediafile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='is_validated',
        ),
        migrations.RemoveField(
            model_name='notificationssourcemedia',
            name='is_validated',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationssourcemedia',
            name='sent_date',
            field=models.DateField(auto_now=True),
        ),
    ]
