# Generated by Django 4.2.5 on 2023-10-22 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0011_remove_notifications_sent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='sent_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 13, 10, 46, 822752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='notifications',
            name='validation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationssourcemedia',
            name='sent_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 22, 13, 10, 46, 822752, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='notificationssourcemedia',
            name='validation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
