# Generated by Django 4.2.5 on 2023-10-24 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0012_notifications_sent_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcemediafile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='sourcemediafile',
            name='source_type',
        ),
        migrations.AddField(
            model_name='sourcemediafile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'en attente'), ('rejected', 'rejecter'), ('accepted', 'accepter')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sourcemediafile',
            name='created',
            field=models.DateField(auto_created=True, default=datetime.date(2023, 10, 24)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sent_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 1, 57, 41, 87288, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notificationssourcemedia',
            name='sent_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 1, 57, 41, 87288, tzinfo=datetime.timezone.utc)),
        ),
    ]
