# Generated by Django 4.2.5 on 2023-10-24 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0013_remove_sourcemediafile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemediafile',
            name='source_type',
            field=models.CharField(choices=[('api', 'api'), ('web-scrapping', 'web-scrapping')], default='web-scrapping'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sent_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 1, 59, 48, 688565, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notificationssourcemedia',
            name='sent_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 1, 59, 48, 688565, tzinfo=datetime.timezone.utc)),
        ),
    ]
