# Generated by Django 4.2.5 on 2023-10-24 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0014_sourcemediafile_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='sent_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 2, 43, 46, 761959, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notificationssourcemedia',
            name='sent_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 2, 43, 46, 761959, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sourcemediafile',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
